### ISSUE TITLE
【求助】请问这是你编译出来的内核吗？

### ISSUE THREAD

**Issue by coachpo** [DreamUniverse843/android_device_xiaomi_crux#1]
我最近在尝试编译一个小米crux的内核，我按照小米官方的wiki编的
但是官方源码总编不过去，一个文件有语法错误，您可以帮忙看一下问题在哪里吗？
十分感谢

https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/4034

**Comment by DreamUniverse843** [comment]
这个不是内核，是 TeamWin 的 Device Tree...
https://github.com/Xpsoted/action_build_twrp_device_tree

**Comment by DreamUniverse843** [comment]
至于编译内核的东西我没接触过，帮不上忙...

**Comment by coachpo** [comment]
> 至于编译内核的东西我没接触过，帮不上忙...

ok 谢谢~ 已经放弃了micode 哈哈哈哈
